using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraMove : MonoBehaviour {
    public Camera RaycastCamera;

    private Vector3 _startPoint;
    private Vector3 _cameraStartPoint;
    private Plane _plane;
    void Start() {
        _plane = new Plane(Vector3.up, Vector3.zero);
    }

    void Update() {
        Ray ray = RaycastCamera.ScreenPointToRay(Input.mousePosition);

        float distance;
        _plane.Raycast(ray, out distance);
        Vector3 point = ray.GetPoint(distance);

        if (Input.GetMouseButtonDown(2)) {
            _startPoint = point;
            _cameraStartPoint = transform.position;
        }

        if (Input.GetMouseButton(2)) {
            Vector3 offset = point - _startPoint;
            transform.position = _cameraStartPoint - offset;
        }

        transform.Translate(0, 0, Input.mouseScrollDelta.y);
        RaycastCamera.transform.Translate(0, 0, Input.mouseScrollDelta.y);
    }
}
